Model size: 16406408 parameters
here torch.Size([128, 256]) torch.Size([128, 256])
Traceback (most recent call last):
  File "/root/wiki-base/wiki2/train.py", line 173, in <module>
    main(args.total_epochs, args.save_every, args.warmup_epochs)
  File "/root/wiki-base/wiki2/train.py", line 160, in main
    trainer.train(total_epochs)
  File "/root/wiki-base/wiki2/train.py", line 143, in train
    self._run_epoch(epoch)
  File "/root/wiki-base/wiki2/train.py", line 109, in _run_epoch
    self._run_batch(xtr, ytr)
  File "/root/wiki-base/wiki2/train.py", line 96, in _run_batch
    _, loss = self.model(xtr, ytr)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/wiki-base/wiki2/models/decoder.py", line 85, in forward
    x = tok_emb + pos_emb # B, T, emb_dim
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.